# Generated by Django 3.2 on 2022-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220305_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Travelers Guide!', max_length=255),
        ),
    ]
